# Generated by Django 5.2.10 on 2026-01-16 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("stock_count", models.IntegerField(default=0)),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "performance_1d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1 day performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_1w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1 week performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_1m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1 month performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_3m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="3 month performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_6m",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="6 month performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_ytd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Year to date performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_1y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="1 year performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_3y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="3 year performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "performance_5y",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="5 year performance %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("average_volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "last_scraped",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Industry",
                "verbose_name_plural": "Industries",
                "ordering": ["-market_cap", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("industries_scraped", models.IntegerField(default=0)),
                ("stocks_scraped", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Scrape Log",
                "verbose_name_plural": "Scrape Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=10, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price change",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "change_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price change %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "market_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "pe_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "eps",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "dividend_yield",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "beta",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "performance_1d",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "performance_1w",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "performance_1m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "performance_ytd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "performance_1y",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("sector", models.CharField(blank=True, max_length=200, null=True)),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
                ("url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "last_scraped",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="stocks.industry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
                "ordering": ["-market_cap", "symbol"],
            },
        ),
    ]
